from silence.sql.tables import DATABASE_SCHEMA, TableField
from silence.logging.default_logger import logger
from silence.__main__ import CONFIG

from typing import List

from os import listdir, getcwd, path, mkdir, makedirs
from shutil import rmtree
import json
import re


# Entry point for the CLI command
def create_api():
    existing_routes_method_pairs = get_user_endpoints()
    logger.info("Found the following user defined endpoints:")
    for rmp in existing_routes_method_pairs:
        logger.info(rmp)

    create_entity_endpoints(existing_routes_method_pairs)


# TODO: GENERATE ENDPOINTS ON RUNTIME WITHOUT READING FROM THE _auto file


# Get the entities from the database and the existing user endpoints and
# create CRUD endpoint files (json) for the remaining ones.
def create_entity_endpoints(existing_routes_method_pairs):
    """
    Reset the "auto" folder for endpoints and iterate over the databases tables and views,
    generating the corresponding endpoints for each of them.
    """
    # Remove the folder if it exists and create it again
    auto_dir = getcwd() + "/endpoints/_auto"

    # Load the database's schema
    DATABASE_SCHEMA.load_tables()

    try:
        rmtree(auto_dir)
    except FileNotFoundError:
        logger.debug("Endpoint folder not found.")

    logger.debug("Creating directory %s", auto_dir)
    makedirs(auto_dir)

    for table in DATABASE_SCHEMA.tables:
        # We always write all autogenerated endpoints to the JS files,
        # while only new endpoints that have not been defined by the
        # user are added as JSON config files for the server
        endpoints_to_js = {}
        endpoints_to_json = {}
        logger.info("Generating endpoints and JS API files for %s", table.name)

        (route_one, pk) = ("", "")
        if not table.is_view:
            pk = table.primary_key_field
            route_one = f"/{table.name.casefold()}/${pk}"

        # Create the basic CRUD endpoints if they haven't been defined yet
        route_all = f"/{table.name.casefold()}"
        crud_endpoints = [
            ("GET", "getAll", route_all),
            ("GET", "getById", route_one),
            ("POST", "create", route_all),
            ("PUT", "update", route_one),
            ("DELETE", "delete", route_one),
        ]

        # example:
        # [('GET', 'getAll', '/departments'),
        #  ('GET', 'getById', '/departments/$departmentId'),
        #  ('POST', 'create', '/departments'),
        #  ('PUT', 'update', '/departments/$departmentId'),
        #  ('DELETE', 'delete', '/departments/$departmentId')]

        for method, name, route in crud_endpoints:
            # If this is a view or a table without a PK, create only "getAll"
            if name != "getAll" and (table.is_view or pk is None):
                continue
            endpoints_to_js[name] = make_endpoint_data(
                name, route, method, table.name, table.fields, pk
            )
            if (route, method) not in existing_routes_method_pairs:
                endpoints_to_json[name] = endpoints_to_js[name]

        # Create *all* the .js files for the API.
        generate_API_file_for_endpoints(endpoints_to_js, table.name, pk)

        # Save the *new* endpoints as JSON config to a file
        if endpoints_to_json:
            json_str = json.dumps(endpoints_to_json, indent=4)
            with open(auto_dir + f"/{table.name}.json", "w", encoding="utf8") as f:
                f.write(json_str)

    # Finally, generate the .js API module for the allowed auth operations
    auth_endpoints = {}
    if CONFIG.get().app.auth.enable:
        auth_endpoints["login"] = {
            "route": "/login",
            "method": "POST",
            "description": "Logs in using an identifier and password",
        }

    if CONFIG.get().app.auth.allow_signup:
        auth_endpoints["register"] = {
            "route": "/register",
            "method": "POST",
            "description": "Registers a new user and stores the password safely in the database",
        }

    if auth_endpoints:
        generate_API_file_for_endpoints(auth_endpoints, "auth", None)


###############################################################################
# Creates a dict with the auto-generated data for a basic CRUD endpoint
##############################################################################
def make_endpoint_data(name, route, method, table_name, cols: List[TableField], pk):
    sql, desc = {
        "getAll": (
            f"SELECT * FROM {table_name}",
            f"Gets all entries from '{table_name}'",
        ),
        "getById": (
            f"SELECT * FROM {table_name} WHERE {pk} = ${pk}",
            f"Gets an entry from '{table_name}' by its primary key",
        ),
        "create": (
            f"INSERT INTO {table_name} "
            + params_to_string(cols)
            + " VALUES "
            + params_to_string(cols, "$"),
            f"Creates a new entry in '{table_name}'",
        ),
        "update": (
            f"UPDATE {table_name} SET "
            + params_to_string(cols, is_update=True)
            + f" WHERE {pk} = ${pk}",
            f"Updates an existing entry in '{table_name}' by its primary key",
        ),
        "delete": (
            f"DELETE FROM {table_name} WHERE {pk} = ${pk}",
            f"Deletes an existing entry in '{table_name}' by its primary key",
        ),
    }[name]

    data = {
        "description": desc,
        "route": route,
        "method": method,
        "sql": sql,
        "request_body_params": [field.name for field in cols],
        "auth_required": method != "GET",
        "allowed_roles": ["*"],
    }

    if method not in ("POST", "PUT"):
        del data["request_body_params"]

    return data


###############################################################################
# Create generic .js files to consume the created endpoints.
###############################################################################
def generate_API_file_for_endpoints(endpoints, table_name, pk_name):
    api_path = getcwd() + "/web/js/api"

    if not path.isdir(api_path):
        makedirs(api_path)

    functions = [
        generate_api_text(ep_name, pk_name, ep_data)
        for ep_name, ep_data in endpoints.items()
    ]
    functions_str = "\n\n    ".join(functions)

    file_content = f"""/*
 * DO NOT EDIT THIS FILE, it is auto-generated. It will be updated automatically.
 * All changes done to this file will be lost upon re-running the 'silence createapi' command.
 * If you want to create new API methods, define them in a new file.
 *
 * Silence is built and maintained by the DEAL research group at the University of Seville.
 * You can find us at https://deal.us.es
 */

"use strict";

import {{ BASE_URL, requestOptions }} from './common.js';

const {table_name}API_auto = {{

    {functions_str}
}};

export {{ {table_name}API_auto }};"""

    open(f"{api_path}/_{table_name}.js", "w", encoding="utf8").write(file_content)


def generate_api_text(name, pk_name, endpoint_data):
    method = endpoint_data["method"].lower()
    route = endpoint_data["route"]
    description = endpoint_data["description"]

    # Replace the URL params with JS's string interpolation method
    if "$" in route:
        route = re.sub(r"\$(\w+)", r"${\1}", route)

    is_getById = name == "getById"
    needs_formdata = method in ("post", "put")
    formdata = ", formData" if needs_formdata else ""

    args = []
    if needs_formdata:
        args.append("formData")

    if method in ("put", "delete") or is_getById:
        args.append(pk_name)

    return f"""/** {description} */
    {name}: async function({", ".join(args)}) {{
        let response = await axios.{method}(`${{BASE_URL}}{route}`{formdata}, requestOptions);
        return response.data{"[0]" if is_getById else ""};
    }},"""


def get_user_endpoints():
    """
    Searches in the endpoints directory of the silence project for every .json file which we assume is an endpoint file.
    gets the route and method as pairs for every endpoint found and returns them
    """
    logger.debug("Looking for user endpoints")
    endpoints_dir = getcwd() + "/endpoints"

    # Create the endpoints dir if its not there
    if not path.isdir(endpoints_dir):
        mkdir(endpoints_dir)

    # Get every .json file in the directory
    user_endpoints = [
        endpoints_dir + f"/{f}" for f in listdir(endpoints_dir) if f.endswith(".json")
    ]
    endpoint_route_method_pairs = []

    # Form (route, method) pairs for every endpoint found and return them
    for jsonfile in user_endpoints:
        with open(jsonfile, "r", encoding="utf8") as ep:
            endpoints = list(json.load(ep).values())
            endpoint_pair = [
                (endpoint["route"], endpoint["method"]) for endpoint in endpoints
            ]
            endpoint_route_method_pairs += endpoint_pair

    return endpoint_route_method_pairs


def params_to_string(param_list: List[TableField], char_add="", is_update=False):
    def add_pref(x):
        return char_add + x if not is_update else f"{x} = ${x}"

    res = ", ".join(add_pref(x.name) for x in param_list)
    return f"({res})" if not is_update else res
